# Generated by Django 6.0.5 on 2026-06-08 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reels', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='reel',
            name='ratio',
            field=models.CharField(choices=[('9:16', '9:16 — Vertical (default)'), ('1:1', '1:1 — Square'), ('4:5', '4:5 — Portrait')], default='9:16', max_length=4),
        ),
        migrations.AddField(
            model_name='reel',
            name='views',
            field=models.PositiveBigIntegerField(default=0),
        ),
    ]
